openapi: 3.0.0
info:
  title: Carrito de Compras API
  description: API para manejar carritos de compras en el sistema de E-Commerce.
  version: "1.0.0"
paths:
  /carts:
    post:
      summary: Crear un nuevo carrito
      responses:
        "200":
          description: Carrito creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      type: object
                  mensaje:
                    type: string
        "400":
          description: Error al crear el carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string

  /carts/{cid}:
    get:
      summary: Obtener un carrito por ID
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        "200":
          description: Carrito encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object
        "400":
          description: Error al buscar el carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string

    put:
      summary: Actualizar un carrito por ID
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  product:
                    type: string
                  quantity:
                    type: integer
      responses:
        "200":
          description: Carrito actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  mensaje:
                    type: string
        "400":
          description: Error al actualizar el carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string

    delete:
      summary: Vaciar un carrito por ID
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        "200":
          description: Carrito vaciado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  mensaje:
                    type: string
        "400":
          description: Error al vaciar el carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string

  /carts/{cid}/product/{pid}:
    post:
      summary: Agregar un producto al carrito
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        "200":
          description: Producto agregado exitosamente al carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  mensaje:
                    type: string
        "400":
          description: Error al agregar el producto al carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string

    put:
      summary: Actualizar la cantidad de un producto en el carrito
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        "200":
          description: Cantidad del producto actualizada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  mensaje:
                    type: string
        "400":
          description: Error al actualizar la cantidad del producto en el carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string

    delete:
      summary: Eliminar un producto del carrito
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        "200":
          description: Producto eliminado exitosamente del carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  mensaje:
                    type: string
        "400":
          description: Error al eliminar el producto del carrito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string

  /carts/{cid}/purchase:
    post:
      summary: Realizar la compra del carrito
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        "200":
          description: Compra realizada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  mensaje:
                    type: string
        "400":
          description: Error al realizar la compra
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string
